Switch Aggregators to a single script backed by OOP
projectfluent/arewefluentyet.com pull request #14
Opened 2019-09-25 00:52 UTC by zbraniecki

Fixes #12.

2019-09-25 16:50 UTC, Pike requested changes
This looks much better, got a bunch of nits, though.

Globally, could you run `flake8` on the code? There's a few things around shadowed and unused imports, etc.

Also, the `README.md` should get an update for the newly required argument.

`aggregate.py` also looks like it could use some OOP, but that's also fine to follow up on.

The actual `milestone?.py` files are fine, hard to denote in the review here.

2019-09-25 16:50 UTC, Pike commented on src/arewefluentyet/source.py
> +            ], check=True, capture_output=True, text=True)
`text` is py3.7 only, I think `encoding` is actually closer to what you want here. Same for the other `subprocess.run` below. (Even more so because I think hg isn't utf-8.)

2019-09-25 16:50 UTC, Pike commented on src/arewefluentyet/source.py
> +    current_revision = None
Set both of those in `__init__`? They're not really meaningful on the class.

2019-09-25 16:50 UTC, Pike commented on src/arewefluentyet/source.py
> +                "-s", bookmark, "-d", revision
`-b` might be better than `-s` in this case. Probably nothing new in this patch, just a ride-along.

2019-09-25 16:50 UTC, Pike commented on src/arewefluentyet/milestone.py
> +    progress_data = None
`name` and `start_date` are good class members, but fold `data_path` and `progress_data` into `__init__`?

2019-09-25 16:50 UTC, Pike commented on src/arewefluentyet/milestone.py
> +    def has_log_for_date(self, source, date):
Can you add a comment on what this does, and why `return False` is a good default behavior?

2019-09-25 16:50 UTC, Pike commented on src/arewefluentyet/milestone.py
> +        result = self.get_data(source, date, revision)
Can you add a method to the base class for this?

```python
    def get_data(self, date, revision):
        raise NotImplementedError
```

2019-09-25 19:40 UTC, zbraniecki commented on src/arewefluentyet/source.py
> +            ], check=True, capture_output=True, text=True)
Does it mean I should use `encoding="ascii"` or `encoding="utf-8"`? (all my commands should be ascii only)

2019-09-25 20:35 UTC, Pike commented on src/arewefluentyet/source.py
> +            ], check=True, capture_output=True, text=True)
I'd suggest ASCII. You can look at the code paths in https://www.mercurial-scm.org/repo/hg/file/tip/mercurial/encoding.py and weep on the encoding story of hg :-/

2019-09-26 10:14 UTC, Pike approved these changes
Thanks.

Did another pass on flake8, and while I don't care much about the line lengths, the regex fix would be nice still.

r=me with that.

2019-09-26 10:14 UTC, Pike commented on src/arewefluentyet/milestone2.py
> +            match = re.match("([0-9]+) (.*?) \[\"([^\"]+)\"\:([0-9]+)\:([0-9]+)\]", line)
From flake8,

```
src/arewefluentyet/milestone2.py:120:46: W605 invalid escape sequence '\['
src/arewefluentyet/milestone2.py:120:60: W605 invalid escape sequence '\:'
src/arewefluentyet/milestone2.py:120:70: W605 invalid escape sequence '\:'
src/arewefluentyet/milestone2.py:120:80: W605 invalid escape sequence '\]'
```

which is fixed with

```python
            match = re.match("([0-9]+) (.*?) [\"([^\"]+)\":([0-9]+):([0-9]+)]", line)
```

2019-09-26 12:25 UTC, merged