Extract snapshot from progress
projectfluent/arewefluentyet.com pull request #4
Opened 2019-08-16 23:03 UTC by zbraniecki

This PR extracts snapshot information from the progress.json.

The main reason for that is that the progress.json is growing (currently at 1.7mb) while none of the detailed information is being used.

The extraction gives us a drastic reduction in size (`progress.json` is 12kb), and separately it adds a `snapshot.json` which has detailed information for the latest revision.

The latter will be used for a detailed list view.

2019-08-16 23:03 UTC, zbraniecki commented
Here's the script I used to create it - https://gist.github.com/zbraniecki/422e08e23318ddf558de478c7cec8bc5

2019-08-19 09:23 UTC, Pike requested changes
I'd like to see the corresponding code PR, too.

I'm sad to loose data, but looking at it, the data's not worth keeping in it's current state anyway.

We might want to do code fixes that ensure what's actually in the `snapshot.json`.

2019-08-19 16:01 UTC, zbraniecki commented
> I'd like to see the corresponding code PR, too.

Which code?

One I'll be using to generate new `snapshot.json` once per week or the list.html/js view of the snapshot?
The former is easy, the latter is very WIPy now.

2019-08-19 16:05 UTC, Pike commented
We can't merge this while not having both, right?

2019-08-19 16:36 UTC, zbraniecki commented
> We can't merge this while not having both, right?

I think we can, but don't need to :)

We never had "official" aggregation script - I used something written based on the snippet you did.
I would like to have propose one, and it'll be a separate PR.

For the snapshot.json, I'm going to introduce the list.html view.

Okay, let me push those two PRs then and we can get back to this one!

2019-08-19 18:25 UTC, zbraniecki commented
Here's the POC of the script I'm using: https://gist.github.com/zbraniecki/422e08e23318ddf558de478c7cec8bc5#file-aggregate-py

2019-08-19 19:14 UTC, zbraniecki commented
Filed #5 to land the script

2019-08-19 19:43 UTC, zbraniecki commented
And #6 for the WIP of the theme redesign - the list.html/js is the snapshot view.

You can see the redesign in action in https://labs.braniecki.net/awfy/gh-pages/ and the list view https://labs.braniecki.net/awfy/gh-pages/list.html

2019-08-22 08:44 UTC, Pike approved these changes
This looks OK, but we shouldn't merge it until we have the code bits ready.

2019-08-22 18:50 UTC, merged