Add M1 aggregation script
projectfluent/arewefluentyet.com pull request #7
Opened 2019-08-20 19:37 UTC by zbraniecki

This adds M1 aggregation script.

2019-08-22 19:57 UTC, zbraniecki commented
This is a second aggregation script which collects all DTD and fluent references from browser.xhtml & its includes for M1.

2019-09-04 10:47 UTC, Pike requested changes
There's a few things to clean up here still.

2019-09-04 10:47 UTC, Pike commented on src/arewefluentyet/aggregate-m1.py
> +def extract_progress(dataset):
This is left-over from `-m3`, and unused here, right? If so, remove please.

2019-09-04 10:47 UTC, Pike commented on src/arewefluentyet/aggregate-m1.py
> +    progress = {}
Use a `defaultdict(int)` instead here? That'll make the code below a good deal nicer.

2019-09-04 10:47 UTC, Pike commented on src/arewefluentyet/aggregate-m1.py
> +    snapshot = {"date": str(next_date), "revision": next_revision, "data": entries}
This would be a nice fix both here and in `m3`, create the snapshot first, and then add it to the `progress_data`.

Should the code around the actual data gathering be factored into `helper.py`?

2019-09-04 10:47 UTC, Pike commented on src/arewefluentyet/aggregate-m1.py
> +def main(mc_path, gh_pages_data_path):
Same question here, most of this code is shared with `m3`, right?

2019-09-04 10:47 UTC, Pike commented on src/arewefluentyet/aggregate-m1.py
> +                        metavar='../awfy/gh-pages/data',
Both here and in `m3`, you probably want to change the `metavar` to point to the actual subdir?

2019-09-04 10:47 UTC, Pike commented on src/arewefluentyet/aggregate-m1.py
> +    new_dir = os.path.split(path)[0]
`os.path.dirname` is more explicit. Also, if you join the full path, you can get around with just one directory parameter.

2019-09-04 10:47 UTC, Pike commented on src/arewefluentyet/aggregate-m1.py
> +                      raw_data)
It took me a bit to realize that `load_include` is recursive. Looking at it in more detail, I realized that lines 50-54 are effectively the same as `load_include`, if you call it with `mc_path` and `.`. In particular, if you use `mc_path` as `dirname` and join with that, I think you should be OK to just keep the current directory around, and not the relative dir and the mc dir.

2019-09-04 10:47 UTC, Pike commented on src/arewefluentyet/aggregate-m1.py
> +        entries.append({"type": "ftl", "id": match})
```python
matches.extend(({"type": "ftl", "id": match} for match in matches))
```

is more" pythonic".

2019-09-04 22:52 UTC, zbraniecki commented on src/arewefluentyet/aggregate-m1.py
> +                        metavar='../awfy/gh-pages/data',
no, I take the `./data` directory here, and create my `./data/M1`, `./data/M3` etc. path depending on the script. This allows you to pass the same `gh-pages-data` to all scripts.

2019-09-04 23:49 UTC, zbraniecki commented
Thank you @Pike! Applied your feedback and factored out most of the code to helper. Looks much easier to read now I think!

2019-09-05 10:52 UTC, Pike approved these changes
Yeah, this looks good, thanks. r=me

2019-09-05 15:17 UTC, merged